In [52]:
import numpy as np
import pandas as pd
import os
import cv2
from tqdm import tqdm

img_dir = "processed_images"
image_size = 224

In [53]:
df = pd.read_csv("data.csv")
df.reset_index()

processed_df = pd.DataFrame(columns=["file", "x", "y"])

df

                                                   file    x    y
0                                08813216-Figure1-1.png   50  368
1                                08813216-Figure4-1.png  135  265
2          1-s2.0-S0009250913008336-main-Figure10-1.png   55  348
3          1-s2.0-S0009250913008336-main-Figure11-1.png   56  356
4           1-s2.0-S0009250913008336-main-Figure2-1.png   59  361
...                                                 ...  ...  ...
1249  Wagner2018_Article_HydrothermalConversionOfLip...   68  215
1250                             wene.319-Figure5-1.png   57  276
1251                             wene.319-Figure6-1.png   58  284
1252  Xie2019_Article_DewaterabilityEnhancementAndHe...   56  295
1253  Yu2014_Article_NutrientFlowsAndQualityOfBio-c-...   70  476

[1254 rows x 3 columns]

In [54]:
for i in tqdm(range(df.shape[0])):
    data = df.iloc[i]
    image = cv2.imread(os.path.join(img_dir, data['file']))
    height, width, _ = image.shape
    
    processed_y = int((data['y']*image_size) / height)
    processed_x = int((data['x']*image_size) / width)
    
    processed_data = {'file' : data['file'], 'x': processed_x, 'y': processed_y}
    processed_df = processed_df.append(processed_data, ignore_index=True)

100%|█████████████████████████████████████████████████████████████████████████████| 1254/1254 [00:03<00:00, 324.13it/s]

In [55]:
processed_df

                                                   file   x    y
0                                08813216-Figure1-1.png  22  209
1                                08813216-Figure4-1.png  60  192
2          1-s2.0-S0009250913008336-main-Figure10-1.png  25  195
3          1-s2.0-S0009250913008336-main-Figure11-1.png  25  196
4           1-s2.0-S0009250913008336-main-Figure2-1.png  26  196
...                                                 ...  ..  ...
1249  Wagner2018_Article_HydrothermalConversionOfLip...  36  162
1250                             wene.319-Figure5-1.png  22  188
1251                             wene.319-Figure6-1.png  20  187
1252  Xie2019_Article_DewaterabilityEnhancementAndHe...  25  188
1253  Yu2014_Article_NutrientFlowsAndQualityOfBio-c-...  23  193

[1254 rows x 3 columns]

In [56]:
processed_df.to_csv("processed_data.csv")

In [57]:
train = processed_df.iloc[:125*8]
valid = processed_df.iloc[125*8:125*9]
test = processed_df.iloc[125*9:]

In [58]:
train.set_index("file", inplace=True)
valid.set_index("file", inplace=True)
test.set_index("file", inplace=True)



print(train.shape)
print(valid.shape)
print(test.shape)

(1000, 2)
(125, 2)
(129, 2)

In [59]:
train.to_csv("train.csv")
valid.to_csv("valid.csv")
test.to_csv("test.csv")